server {
    listen 80;
    server_name colibrimoveis.com.br www.colibrimoveis.com.br;
    return 301 https://$host$request_uri;
}

map $http_user_agent $prerender_ua {
    default       0;
    "~*Prerender" 0;

    "~*googlebot"                               1;
    "~*yahoo!\ slurp"                           1;
    "~*bingbot"                                 1;
    "~*yandex"                                  1;
    "~*baiduspider"                             1;
    "~*facebookexternalhit"                     1;
    "~*twitterbot"                              1;
    "~*rogerbot"                                1;
    "~*linkedinbot"                             1;
    "~*embedly"                                 1;
    "~*quora\ link\ preview"                    1;
    "~*showyoubot"                              1;
    "~*outbrain"                                1;
    "~*pinterest\/0\."                          1;
    "~*developers.google.com\/\+\/web\/snippet" 1;
    "~*slackbot"                                1;
    "~*vkshare"                                 1;
    "~*w3c_validator"                           1;
    "~*redditbot"                               1;
    "~*applebot"                                1;
    "~*whatsapp"                                1;
    "~*flipboard"                               1;
    "~*tumblr"                                  1;
    "~*bitlybot"                                1;
    "~*skypeuripreview"                         1;
    "~*nuzzel"                                  1;
    "~*discordbot"                              1;
    "~*google\ page\ speed"                     1;
    "~*qwantify"                                1;
    "~*pinterestbot"                            1;
    "~*bitrix\ link\ preview"                   1;
    "~*xing-contenttabreceiver"                 1;
    "~*chrome-lighthouse"                       1;
    "~*telegrambot"                             1;
}

map $args $prerender {
    default $prerender_ua;
    "~(^|&)_escaped_fragment_=" 1;
}

server {
    listen 443 ssl;
    server_name colibrimoveis.com.br www.colibrimoveis.com.br;

    if ($host = 'colibrimoveis.com.br') {
        return 301 https://www.colibrimoveis.com.br$request_uri;
    }

    ssl_certificate /etc/letsencrypt/live/colibrimoveis.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/colibrimoveis.com.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 24M;

    location / {
        root   /var/www/colibri/front-web/build/;
        index  index.html;
        try_files $uri @prerender;
    }

    location /api/ {
        proxy_pass http://localhost:3014/;
    }

    location /files/ {
        alias /var/www/colibri/storage/uploads;
    }

    location /sitemap/ {
		proxy_pass http://localhost:3014/sitemap/;
    }

    location @prerender {
		proxy_set_header X-Prerender-Token Cf1c4qzjAydlRjcvSuaH;	
		resolver 8.8.8.8;	
		if ($prerender = 1) {		
			set $proxyprerender "service.prerender.io";        
	    		rewrite .* /$scheme://$host$request_uri? break;
	   		proxy_pass http://$proxyprerender;
		}

		if ($prerender = 0) {
			root   /var/www/colibri/front-web/build/;
			expires 1d;
			add_header Cache-Control "public";		
			rewrite .* /index.html break;
		}		
	}
}